// 03-svelte/1.1.3-first+webp/src/components/Navbar.svelte
<script>
// @ts-nocheck
    import UIkit from 'uikit';
    import Icons from 'uikit/dist/js/uikit-icons';
    UIkit.use(Icons);

    let logo = '/assets/logo.png'
  </script>
    
<!--for small devices-->
<div id="navbar" class="uk-hidden@xl uk-hidden@l uk-hidden@m uk-hidden@s uk-position-bottom">
  <div uk-sticky="start: 170; position: bottom; animation: uk-animation-slide-bottom; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-dark; end: !html; offset: 0">
    <nav class="uk-navbar-container">
      <div class="uk-container">
        <div uk-navbar>
          <a href="#filtration" class="uk-navbar-item uk-logo" uk-scroll>
              <img src="{logo}" alt="logo" />
          </a>
          <div class="uk-navbar-left">
              <ul class="uk-navbar-nav">
              <li><a href="#manage-category" uk-toggle>Category</a></li>
              </ul>
          </div>
          <div class="uk-navbar-right">
              <ul class="uk-navbar-nav">
              <li>
                  <a href="#add-task" class="uk-position-relative" uk-toggle>
                  <span class="uk-icon-button" uk-icon="icon: plus"></span>
                  </a>
              </li>
              </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>
<!--for bigger devices-->
<div id="navbar" class="uk-hidden-xs">
  <div uk-sticky="start: 170; animation: uk-animation-slide-top; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-dark; end: !main; offset: 0">
    <nav class="uk-navbar-container">
      <div class="uk-container">
        <div uk-navbar>
          <a href="#filtration" class="uk-navbar-item uk-logo" uk-scroll>
              <img src="{logo}" alt="logo" />
          </a>
          <div class="uk-navbar-left">
              <ul class="uk-navbar-nav">
              <li><a href="#manage-category" uk-toggle>Category</a></li>
              </ul>
          </div>
          <div class="uk-navbar-right">
              <ul class="uk-navbar-nav">
              <li>
                  <a href="#add-task" class="uk-position-relative" uk-toggle>
                  <span class="uk-icon-button" uk-icon="icon: plus"></span>
                  </a>
              </li>
              </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>
  
  <style>
    .uk-navbar-container:not(.uk-navbar-transparent) {
      background: #717182 !important;
      color: #e1e1e8;
    }
    .uk-navbar-nav > li > a {
      justify-content: left !important;
      width: 9vw;
      font-weight: bold;
      color: #e1e1e8 !important;
    }
    .uk-navbar-nav > li > a:hover {
      color: #636365 !important;
    }
    .uk-navbar-nav > li:first-child > a {
      justify-content: center !important;
      width: 12vw;
    }
    .uk-logo img {
      width: 3rem;
      margin-right: 1rem;
    }

    .uk-hidden-xs { visibility: hidden; }


  </style>

// 02-react/1.2.2-first-img+comp/src/components/Navbar.jsx
import React from 'react';

const Navbar = ({ handleAddTask }) => {
  let logo = '/assets/logo.png';
  return (
    <div>
      {/* Navbar for small devices */}
      <div id="navbar" className="uk-hidden@xl uk-hidden@l uk-hidden@m uk-hidden@s uk-position-bottom">
        <div uk-sticky="start: 170; position: bottom; animation: uk-animation-slide-bottom; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-dark; end: !html; offset: 0">
          <nav className="uk-navbar-container">
            <div className="uk-container">
              <div uk-navbar="true">
                <a href="#filtration" className="uk-navbar-item uk-logo" uk-scroll="true">
                  <img src={logo} alt="logo" width="40" height="40" />
                </a>
                <div className="uk-navbar-left">
                  <ul className="uk-navbar-nav">
                    <li>
                      <a href="" uk-toggle="target: #manage-category" >Category</a>
                    </li>
                  </ul>
                </div>
                <div className="uk-navbar-right">
                  <ul className="uk-navbar-nav">
                    <li>
                      <a href="" className="uk-position-relative" uk-toggle="target: #add-task" onClick={handleAddTask}>
                        <span className="uk-icon-button" uk-icon="icon: plus"></span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>

      {/* Navbar for larger devices */}
      <div id="navbar" className="uk-hidden-xs">
        <div uk-sticky="start: 170; animation: uk-animation-slide-top; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-dark; end: !body; offset: 0">
          <nav className="uk-navbar-container">
            <div className="uk-container">
              <div uk-navbar="true">
                <a href="#filtration" className="uk-navbar-item uk-logo" uk-scroll="true">
                  <img src={logo} alt="logo" width="40" height="40" />
                </a>
                <div className="uk-navbar-left">
                  <ul className="uk-navbar-nav">
                    <li>
                      <a href="" uk-toggle="target: #manage-category">Category</a>
                    </li>
                  </ul>
                </div>
                <div className="uk-navbar-right">
                  <ul className="uk-navbar-nav">
                    <li>
                      <a href="" className="uk-position-relative" uk-toggle="target: #add-task" onClick={handleAddTask}>
                        <span className="uk-icon-button" uk-icon="icon: plus"></span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>
  );
};

export default Navbar;
