// 01-angular/1.1.1-first+files/src/app/components/task-list/task-list.component.ts
import { Component, OnInit } from '@angular/core';
import { TaskService } from '../../services/task.service';
import { Task } from '../../models/task';
import { TaskComponent } from '../task/task.component';
import { TaskFilterComponent } from '../task-filter/task-filter.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-task-list',
  templateUrl: './task-list.component.html',
  styleUrls: ['./task-list.component.css'],
  standalone: true,
  imports: [TaskComponent, CommonModule ,TaskFilterComponent]
})
export class TaskListComponent implements OnInit {
  tasks: Task[] = [];
  filters: { searchQuery: string; filterStatus: string; filterCategory: string | number } = {
    searchQuery: '',
    filterStatus: 'ALL',
    filterCategory: 'ALL'
  };

  constructor(private taskService: TaskService) {}

  ngOnInit(): void {
    this.taskService.tasks$.subscribe(tasks => {
      this.tasks = tasks;
    });
  }

  applyFilters(event: { searchQuery: string; filterStatus: string; filterCategory: string | number }): void {
    this.filters = event;
  }

  filterTasks(task: Task): boolean {
    const matchesSearchQuery = task.title.toLowerCase().includes(this.filters.searchQuery.toLowerCase());
    const matchesStatus = this.filters.filterStatus === 'ALL' || task.status === this.filters.filterStatus;
    const matchesCategory = this.filters.filterCategory === 'ALL' || task.category === this.filters.filterCategory;

    return matchesSearchQuery && matchesStatus && matchesCategory;
  }
}

// 03-svelte/1.2.1-first-img+files/src/components/TaskList.svelte
<script>
    import Task from './Task.svelte';
    import { tasks } from '../stores/store';
    import TaskFilter from './TaskFilter.svelte';

let filters = {
  searchQuery: '',
  filterStatus: 'ALL',
  filterCategory: 'ALL'
};

function applyFilters(event) {
  filters = event.detail;
}

function filterTasks(task) {
  const matchesSearchQuery = task.title.toLowerCase().includes(filters.searchQuery.toLowerCase());
  const matchesStatus = filters.filterStatus === 'ALL' || task.status === filters.filterStatus;
  const matchesCategory = filters.filterCategory === 'ALL' || task.category === filters.filterCategory;

  return matchesSearchQuery && matchesStatus && matchesCategory;
}
</script>

<TaskFilter/>
  <div id="taskList">
    <ul class="uk-comment-list js-filter">
      {#each $tasks as task}
        <li data-cat={task.category} data-due={task.end_at} data-done={task.status} data-priority={task.priority}>
            <Task {task} />
            
            {#if task.is_parent && task.subtasks?.length > 0}
                <ul class="subtask{task.id}" hidden>
                    {#each task.subtasks as subtask}
                        <li>
                        <Task task={subtask} />
                        </li>
                    {/each}
                </ul>
            {/if}
        </li>
      {/each}
    </ul>
  </div>
  
  <style>
    #taskList {
      width: 92vw;
    }
  </style>
