// 01-angular/2.3.3-struct-all+webp/src/app/components/add-task-modal/add-task-modal.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { Task } from '../../models/task';
import { Category } from '../../models/category';
import { TaskService } from '../../services/task.service';
import { CategoryService } from '../../services/category.service';
import { Observable } from 'rxjs';
import UIkit from 'uikit';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-add-task-modal',
  templateUrl: './add-task-modal.component.html',
  styleUrls: ['./add-task-modal.component.css'],
  standalone: true,
  imports: [CommonModule, FormsModule],
})
export class AddTaskModalComponent implements OnInit {
  @Input() is_subtask = false;
  @Output() taskAdded = new EventEmitter<Task>();

  title = '';
  description = '';
  dueDate = new Date().toISOString().substring(0, 10);
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT' = 'LOW';
  category = '';
  parent: number | null = null;
  categoriesList$: Observable<Category[]>;
  tasksList$: Observable<Task[]>;


  constructor(private taskService: TaskService, private categoryService: CategoryService) {
    this.categoriesList$ = this.categoryService.categories$;
    this.tasksList$ = this.taskService.tasks$;
  }

  ngOnInit(): void {}

  handleAddTask(): void {
    const newTask: Task = {
      id: 0,
      title: this.title,
      description: this.description,
      end_at: new Date(this.dueDate).toISOString(),
      priority: this.priority,
      category: parseInt(this.category, 10),
      attachments: [],
      subtasks: [],
      parent: this.is_subtask ? this.parent : null,
      status: 'TODO',
      created_at: new Date().toISOString(),
      is_parent: !this.is_subtask
    };

    this.taskService.addTask(newTask);
    UIkit.modal('#add-task').hide();
    this.taskAdded.emit(newTask);
    this.resetForm();
  }

  private resetForm(): void {
    this.title = '';
    this.description = '';
    this.dueDate = new Date().toISOString().substring(0, 10);;
    this.priority = 'LOW';
    this.category = '';
    this.parent = null;
  }
}

// 03-svelte/1.1.3-first+webp/src/components/AddTaskModal.svelte
<script>
// @ts-nocheck
    import { createEventDispatcher } from 'svelte';
    import { categories, tasks } from '../stores/store';
    import { addTask } from '../stores/utils';
    import UIkit from 'uikit';

    export let is_subtask = false;
    let today = new Date();
  
    let title = '';
    let description = '';
    let dueDate = today.toISOString().split('T')[0];;
    let priority = 'LOW';
    let category = '';
    let parent = null;
  
    function handleAddTask() {
      const newTask = {
        title,
        description,
        end_at: dueDate,
        priority,
        category,
        attachments: [],
        subtasks: [],
        parent: is_subtask
      };

      addTask(newTask);
      UIkit.modal('#add-task').hide();
    }
  </script>
  
  <div id="add-task" uk-modal>
    <div class="uk-modal-dialog">
      <button class="uk-modal-close-default" type="button" uk-close></button>
      <div class="uk-modal-header">
        <h2 class="uk-modal-title">Add New Task</h2>
      </div>
      <div class="uk-modal-body">
        <form>
          <div class="uk-margin">
            <input id="addTitle" class="uk-input" type="text" name="title" placeholder="Title" bind:value={title} />
          </div>
          <div class="uk-margin">
            <textarea id="addDescription" class="uk-textarea" rows="5" name="description" placeholder="Description" bind:value={description}></textarea>
          </div>
          <div class="uk-margin">
            <label for={dueDate}>Due date</label>
            <input id="addDue_date" class="uk-input" type="date" name="due_date" bind:value={dueDate} />
          </div>
          <div class="uk-margin">
            <label for={priority}>Priority</label>
            <select id="addPriority" class="uk-select" name="priority" bind:value={priority}>
              <option value="LOW">Low</option>
              <option value="MEDIUM">Medium</option>
              <option value="HIGH">High</option>
              <option value="URGENT">Urgent</option>
            </select>
          </div>
          <div class="uk-margin">
            <label for={category}>Category</label>
            <select id="addCategory" class="uk-select" name="category" bind:value={category}>
              {#each $categories as category}
                <option value={category.id}>{category.name}</option>
              {/each}
            </select>
          </div>
          <div class="uk-margin">
            <label for={parent}>Is subtask of:</label>
            <select id="addParent" class="uk-select" name="parent" bind:value={parent}>
              <option value={null}>No Parent</option>
              {#each $tasks as task}
                <option value={task.id}>{task.title}</option>
              {/each}
            </select>
          </div>
        </form>
      </div>
      <div class="uk-modal-footer uk-text-right">
        <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
        <button class="uk-button uk-button-primary" type="button" on:click={handleAddTask}>Add Task</button>
      </div>
    </div>
  </div>
