// 02-react/1.2.2-first-img+comp/src/components/Navbar.jsx
import React from 'react';

const Navbar = ({ handleAddTask }) => {
  let logo = '/assets/logo.png';
  return (
    <div>
      {/* Navbar for small devices */}
      <div id="navbar" className="uk-hidden@xl uk-hidden@l uk-hidden@m uk-hidden@s uk-position-bottom">
        <div uk-sticky="start: 170; position: bottom; animation: uk-animation-slide-bottom; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-dark; end: !html; offset: 0">
          <nav className="uk-navbar-container">
            <div className="uk-container">
              <div uk-navbar="true">
                <a href="#filtration" className="uk-navbar-item uk-logo" uk-scroll="true">
                  <img src={logo} alt="logo" width="40" height="40" />
                </a>
                <div className="uk-navbar-left">
                  <ul className="uk-navbar-nav">
                    <li>
                      <a href="" uk-toggle="target: #manage-category" >Category</a>
                    </li>
                  </ul>
                </div>
                <div className="uk-navbar-right">
                  <ul className="uk-navbar-nav">
                    <li>
                      <a href="" className="uk-position-relative" uk-toggle="target: #add-task" onClick={handleAddTask}>
                        <span className="uk-icon-button" uk-icon="icon: plus"></span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>

      {/* Navbar for larger devices */}
      <div id="navbar" className="uk-hidden-xs">
        <div uk-sticky="start: 170; animation: uk-animation-slide-top; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-dark; end: !body; offset: 0">
          <nav className="uk-navbar-container">
            <div className="uk-container">
              <div uk-navbar="true">
                <a href="#filtration" className="uk-navbar-item uk-logo" uk-scroll="true">
                  <img src={logo} alt="logo" width="40" height="40" />
                </a>
                <div className="uk-navbar-left">
                  <ul className="uk-navbar-nav">
                    <li>
                      <a href="" uk-toggle="target: #manage-category">Category</a>
                    </li>
                  </ul>
                </div>
                <div className="uk-navbar-right">
                  <ul className="uk-navbar-nav">
                    <li>
                      <a href="" className="uk-position-relative" uk-toggle="target: #add-task" onClick={handleAddTask}>
                        <span className="uk-icon-button" uk-icon="icon: plus"></span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>
  );
};

export default Navbar;

// 03-svelte/2.3.3-struct-all+webp/src/components/Navbar.svelte
<script>
// @ts-nocheck

    let logo = "/assets/logo.svg";


    import { createEventDispatcher } from 'svelte';

    const dispatch = createEventDispatcher();

    function handleAddTask() {
      dispatch('add-task');
    }

    function handleManageCategory(event) {
      dispatch('manage-category');
      setTimeout(() => {
        event.target.closest('a').removeAttribute('hidden');
      }, 1);
    }
  </script>

<!--for small devices-->
<div id="navbar" class="uk-hidden@xl uk-hidden@l uk-hidden@m uk-hidden@s uk-position-bottom">
  <div uk-sticky="start: 170; position: bottom; animation: uk-animation-slide-bottom; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-dark; end: !html; offset: 0">
    <nav class="uk-navbar-container">
      <div class="uk-container">
        <div uk-navbar>
          <a href="#filtration" class="uk-navbar-item uk-logo" uk-scroll>
            <!--<img src="{logo}" alt="logo" width="40" height="40" />-->
            <img src={logo} alt="logo" width="40" height="40" />
          </a>
          <div class="uk-navbar-left">
            <ul class="uk-navbar-nav">
              <li>
                <a href="#manage-category" uk-toggle on:click={handleManageCategory}>Category</a>
              </li>
            </ul>
          </div>
          <div class="uk-navbar-right">
            <ul class="uk-navbar-nav">
              <li>
                <a href="#add-task" class="uk-position-relative" uk-toggle on:click={handleAddTask}>
                  <span class="uk-icon-button" uk-icon="icon: plus"></span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>
<!--for bigger devices-->
<div id="navbar" class="uk-hidden-xs">
  <div uk-sticky="start: 170; animation: uk-animation-slide-top; sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-dark; end: !main; offset: 0">
    <nav class="uk-navbar-container">
      <div class="uk-container">
        <div uk-navbar>
          <a href="#filtration" class="uk-navbar-item uk-logo" uk-scroll>
            <img src="{logo}" alt="logo" width="40" height="40" />
          </a>
          <div class="uk-navbar-left">
            <ul class="uk-navbar-nav">
              <li>
                <a href="#manage-category" uk-toggle on:click={handleManageCategory}>Category</a>
              </li>
            </ul>
          </div>
          <div class="uk-navbar-right">
            <ul class="uk-navbar-nav">
              <li>
                <a href="#add-task" class="uk-position-relative" uk-toggle on:click={handleAddTask}>
                  <span class="uk-icon-button" uk-icon="icon: plus"></span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>
