// 01-angular/2.3.2-struct-all+comp/src/app/components/task/task.component.ts
import { Component, Input, OnInit, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Task, Attachment } from '../../models/task';
import { Category } from '../../models/category';
import { TaskService } from '../../services/task.service';
import { AttachmentModalComponent } from '../attachment-modal/attachment-modal.component';
import { SafePipe } from '../../pipe/safe.pipe';
import UIkit from 'uikit';
import { ImageCacheService } from '../../services/cache.service';

@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.css'],
  standalone: true,
  imports: [CommonModule, AttachmentModalComponent, FormsModule, SafePipe]
})
export class TaskComponent implements OnInit, AfterViewInit {
  @Input() task!: Task;
  tasks: Task[] = [];
  categories: Category[] = [];
  isEditing = false;
  showDescription = false;
  percentage = 0;
  is_subtask = false;
  title = '';
  description = '';
  dueDate = '';
  id: number = 0;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT' = 'LOW';
  category = 0;
  status: 'TODO' | 'IN_PROGRESS' | 'DONE' = 'TODO';
  formattedEndDate = '';

  constructor(private taskService: TaskService, private imageCacheService: ImageCacheService) {
    this.taskService.tasks$.subscribe(tasks => this.tasks = tasks);
    this.taskService.categories$.subscribe(categories => this.categories = categories);
  }

  setId(number: number): void {
    this.id = number;
    console.log(this.id);
  }

  ngOnInit(): void {
    this.status = this.task.status;
    this.calculateProgress();
    this.formatEndDate();
    this.cacheTaskFiles();
  }

  cacheTaskFiles() {
    if (this.task && this.task.attachments) {
      this.task.attachments.forEach((attach: any) => {
          this.imageCacheService.cacheImage('/compress/' + attach.path);
      });
    }
  }

  ngAfterViewInit(): void {}

  getCategoryColor(catId: number): string {
    const category = this.categories.find(cat => cat.id === catId);
    return category ? category.color : '#fff';
  }

  toggleEdit(): void {
    this.isEditing = !this.isEditing;
    if (this.isEditing) {
      this.title = this.task.title;
      this.description = this.task.description;
      this.dueDate = this.task.end_at.split('T')[0];
      this.priority = this.task.priority;
      this.category = this.task.category;
    }
  }

  saveTask(): void {
    const updatedTask: Task = {
      ...this.task,
      title: this.title,
      description: this.description,
      end_at: new Date(this.dueDate).toISOString(),
      priority: this.priority,
      category: this.category,
    };

    this.taskService.updateTask(updatedTask);
    Object.assign(this.task, updatedTask);
    this.isEditing = false;
  }

  toggleStatus(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.status = this.status === 'TODO' ? 'IN_PROGRESS' : this.status === 'IN_PROGRESS' ? 'DONE' : 'TODO';
    input.checked = this.status !== 'TODO';
    this.taskService.updateTask({ ...this.task, status: this.status });
  }

  removeTask(): void {
    this.taskService.deleteTask(this.task.id);
  }

  calculateProgress(): void {
    const count = this.task.subtasks.length;
    this.percentage = this.task.subtasks.reduce((acc, subtask) => {
      if (subtask.status === 'DONE') acc += 1;
      else if (subtask.status === 'IN_PROGRESS') acc += 0.1;
      else if(this.task.is_parent == false){
        if (this.task.status === 'DONE') acc = 1;
        else if (this.task.status === 'IN_PROGRESS') acc = 0.5;
      }
      return acc;
    }, 0);
    this.percentage = count > 0 ? (this.percentage * 100) / count : this.task.status === 'DONE' ? 100 : 0;
  }

  openSubtaskModal(): void {
    this.is_subtask = true;
    UIkit.modal('#add-task').show();
  }

  toggleDescription(): void {
    this.showDescription = !this.showDescription;
  }

  formatEndDate(): void {
    this.formattedEndDate = this.task.end_at ? new Date(this.task.end_at).toLocaleDateString() : 'No due date';
  }

  openConfirmationDialog(taskId: number): void {
    UIkit.modal.confirm('Are you sure you want to delete this task?').then(() => {
      this.removeTask();
    });
  }

  openLightbox(): void {
    const lightboxItems = this.generateLightboxItems(this.task.attachments);
    UIkit.lightboxPanel({ items: lightboxItems }).show(0);
  }

  generateLightboxItems(attachments: Attachment[]): any[] {
    return attachments.map(att => {
      if (att.type === 'IMAGE') return { source: `/compress/${att.path}`, caption: att.path, type: 'image' };
      if (att.type === 'FILE') return { source: `/compress/${att.path}`, caption: att.path, type: 'iframe' };
      if (att.type === 'VOICE') return { source: `/compress/${att.path}`, caption: att.path, type: 'video', attributes: { autoplay: false } };
      return null;
    }).filter(item => item !== null);
  }
}

<article class="uk-comment uk-visible-toggle" tabindex="-1" role="comment" [ngStyle]="{'border-color': getCategoryColor(task.category)}">
  <div class="task uk-margin-large uk-card uk-card-default {{task.priority.toLowerCase()}}">
    <div class="settings uk-position-top-right uk-position-medium@l uk-hidden-hover">
      <div class="uk-inline uk-align-right">
        <button class="uk-button uk-button-text" type="button">
          <span uk-icon="icon: cog"></span> Settings
        </button>
        <div uk-dropdown="mode: click">
          <ul class="uk-iconnav uk-iconnav-vertical">
            <li><a (click)="setId(task.id)" href="#attach{{task.id}}" uk-toggle><span uk-icon="icon: settings"></span> Attachments</a></li>
            <li><a class="uk-link-muted" (click)="toggleEdit()"><span uk-icon="icon: pencil"></span> Edit task</a></li>
            <li><a id="dialog{{task.id}}" (click)="openConfirmationDialog(task.id)" href="#"><span uk-icon="icon: trash"></span> Delete task</a></li>
            <li><a class="uk-link-muted" (click)="openSubtaskModal()"><span uk-icon="icon: plus"></span> Add Subtask</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div *ngIf="!isEditing">
      <header class="uk-child-width-1-1 uk-child-width-1-2@m uk-child-width-1-2@l uk-child-width-1-2@xl" uk-grid>
        <div>
          <div class="uk-child-width-1-2 uk-text-center" uk-grid>
            <div class="uk-width-auto">
              <input type="checkbox" name="status" [checked]="task.status !== 'TODO'" (change)="toggleStatus($event)" />
            </div>
            <div class="uk-width-expand uk-text-left uk-margin-small-left">
              <h2 class="title uk-align-left" [ngStyle]="{'text-decoration': task.status === 'DONE' ? 'line-through' : 'none'}" name="title" [class.done]="task.status === 'DONE'">
                {{ task.title }}
              </h2>
            </div>
          </div>
        </div>
        <div>
          <div class="uk-child-width-1-2 uk-child-width-1-3@s uk-text-center" uk-grid>
            <div>
              <div>
                <p>{{ percentage.toFixed(0) }}% completed
                  <span *ngIf="task.attachments.length > 0" id="js-lightbox{{task.id}}" (click)="openLightbox()" class="uk-icon uk-icon-image js-lightbox{{task.id}}" style="background-image: url(/img/paperclip.svg);"></span>
                </p>
              </div>
              <div>
                <span *ngIf="task.description" class="uk-button uk-button-text" style="margin: 0px !important;" (click)="toggleDescription()">
                  {{ showDescription ? 'Hide description' : 'Show description' }}
                </span>
              </div>
              <div class="uk-hidden uk-visible@s"></div>
            </div>
            <div>
              <div>
                <h4 type="date" class="due-date uk-text-right uk-text-left@m uk-margin-medium-left@s">
                  {{ formattedEndDate }}
                </h4>
              </div>
              <div></div>
              <div class="uk-visible@m uk-visible@l uk-visible@xl js-lightbox{{task.id}}" (click)="openLightbox()" uk-slider>
                <div class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1">
                  <div class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-3@m">
                    <div *ngFor="let attach of task.attachments">
                      <div *ngIf="attach.type === 'IMAGE'">
                        <div class="uk-cover-container">
                          <canvas></canvas>
                          <img [src]="'/compress/' + attach.path" alt="{{ attach.path }}" uk-cover />
                        </div>
                      </div>
                      <div *ngIf="attach.type === 'FILE'">
                        <div class="uk-cover-container">
                          <canvas></canvas>
                          <iframe [src]="('/compress/' + attach.path) | safe" uk-responsive uk-cover uk-video="automute: true"></iframe>
                        </div>
                      </div>
                      <div *ngIf="attach.type === 'VOICE'">
                        <div class="uk-cover-container" style="border: black 2px solid">
                          <canvas></canvas>
                          <video [src]="'/compress/' + attach.path" uk-responsive uk-cover class="uk-position-center" uk-video="autoplay: false" poster="/img/play-button.svg" style="width: 2vw;"></video>
                        </div>
                      </div>
                    </div>
                  </div>
                  <a class="uk-position-center-left uk-position-small uk-hidden-hover" href uk-slidenav-previous uk-slider-item="previous"></a>
                  <a class="uk-position-center-right uk-position-small uk-hidden-hover" href uk-slidenav-next uk-slider-item="next"></a>
                </div>
                <ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>
              </div>
            </div>
          </div>
        </div>
      </header>
      <div *ngIf="task.description">
        <div class="description uk-child-width-1-1 uk-card-body uk-text-left uk-padding-medium uk-margin-small-bottom" uk-grid [hidden]="!showDescription">
          <div class="descript">
            <p>{{ task.description }}</p>
          </div>
        </div>
      </div>
      <div class="third uk-text-center" uk-grid>
        <div class="uk-width-1-6@m uk-width-1-2 uk-position-bottom-right uk-text-right uk-position-small">
          <a *ngIf="task.is_parent" href="" class="uk-button uk-button-text uk-link-muted" attr.uk-toggle="target: .subtask{{task.id}}">Show subtasks</a>
        </div>
      </div>
    </div>
    <div *ngIf="isEditing">
      <form>
        <header class="uk-child-width-1-1 uk-child-width-1-2@m uk-child-width-1-2@l uk-child-width-1-2@xl" uk-grid>
          <div>
            <div class="uk-child-width-1-2 uk-text-center" uk-grid>
              <div class="uk-width-auto">
                <input id="status{{task.id}}" type="checkbox" name="status" disabled [checked]="true"/>
              </div>
              <div class="uk-width-expand uk-text-left uk-margin-small-left">
                <textarea id="title{{task.id}}" class="title uk-textarea" name="title" [(ngModel)]="title" rows="2"></textarea>
              </div>
            </div>
          </div>
          <div>
            <div class="uk-child-width-1-2 uk-child-width-1-3@s uk-text-center" uk-grid>
              <div>
                <div>
                  <div class="uk-margin">
                    <select id="priority{{task.id}}" class="uk-select" name="category" [(ngModel)]="category">
                      <option *ngFor="let cat of categories" [value]="cat.id" [selected]="cat.id === task.category">{{ cat.name }}</option>
                    </select>
                  </div>
                </div>
              </div>
              <div>
                <div>
                  <input id="due_date{{task.id}}" type="date" name="due_date" class="due-date uk-input" [(ngModel)]="dueDate"/>
                </div>
              </div>
                <div class="uk-hidden uk-visible@s"></div>
            </div>
            <div>
              <div>
                <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">
                  <label><input id="priorityL{{task.id}}" class="uk-radio" type="radio" name="radio" value="LOW" [(ngModel)]="priority">&nbsp;Low</label>
                  <label><input id="priorityM{{task.id}}" class="uk-radio" type="radio" name="radio" value="MEDIUM" [(ngModel)]="priority">&nbsp;Medium</label>
                  <label><input id="priorityH{{task.id}}" class="uk-radio" type="radio" name="radio" value="HIGH" [(ngModel)]="priority">&nbsp;High</label>
                  <label><input id="priorityU{{task.id}}" class="uk-radio" type="radio" name="radio" value="URGENT" [(ngModel)]="priority">&nbsp;Urgent</label>
                </div>
              </div>
            </div>
          </div>
        </header>
        <div id="descript" class="description uk-child-width-1-1 uk-card-body uk-text-left uk-padding-medium uk-margin-small-bottom" uk-grid>
          <div class="descript">
            <textarea id="description{{task.id}}" class="descr uk-textarea" rows="3" name="description" [(ngModel)]="description"></textarea>
          </div>
        </div>
        <div class="third uk-text-center" uk-grid>
          <div class="uk-width-1-6@m uk-width-1-2 uk-position-bottom-right uk-text-right uk-position-small">
            <div class="uk-flex">
              <button class="uk-button uk-button-default" type="button" (click)="toggleEdit()">Cancel</button>
              <button class="uk-button uk-button-primary" type="button" (click)="saveTask()">Save</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</article>
<app-attachment-modal [idTask]="task.id" [attachments]="task.attachments"></app-attachment-modal>

// 02-react/1.1.1-first+files/src/components/Task.jsx
import React, { useEffect, useState } from 'react';

import AddTask from './AddTask';
import Attachement from './Attachement';

import { useTaskManager } from '../store/utils';
import categoryData from '../assets/categories.json';

import 'uikit/dist/css/uikit.css';
import UIkit from 'uikit';


const Task = ({ task  }) => {
  const { updateTask, deleteTask } = useTaskManager();

  const [id, setId] = useState(0);  

  const [title, setTitle] = useState(task.title);
  const [description, setDescription] = useState(task.description);
  const [dueDate, setDueDate] = useState(task.end_at.split('T')[0]);
  const [priority, setPriority] = useState(task.priority);
  const [category, setCategory] = useState(task.category);
  const [status, setStatus] = useState(task.status);
  
  const [isSubtask, setIsSubtask] = useState(false);


  const [lightboxItems, setLightboxItems] = useState([]);

  const cat = categoryData.results.reduce((acc, category) => {
    acc[category.id] = category;
    return acc;
  }, {});

  const [categories, setCategories] = useState([]);
  useEffect(() => {
    if(categories.length == 0)
      setCategories(categoryData.results);
  }, []);

  
  useEffect(() => {
    const dialogSelector = `#dialog${task.id}`;
    const handleClick = async (e) => {
      e.preventDefault();
      try {
        await UIkit.modal.confirm('Are you sure you want to delete this task?');
        removeTask();
      } catch (error) {
        console.warn('Task deletion was cancelled', error);
      }
    };
    UIkit.util.on(dialogSelector, 'click', handleClick);
    return () => {
      UIkit.util.off(dialogSelector, 'click', handleClick);
    };
  }, [task.id]);

  const generateLightboxItems = (attachments) => {
    return attachments.map(att => {
      if (att.type === 'IMAGE') {
        return { source: `/files/${att.path}`, caption: att.path, type: 'image' };
      } else if (att.type === 'FILE') {
        return { source: `/files/${att.path}`, caption: att.path, type: 'iframe' };
      } else if (att.type === 'VOICE') {
        return { source: `/files/${att.path}`, caption: att.path, type: 'video', attributes: { autoplay: false } };
      }
    });
  };

  useEffect(() => {
    const items = generateLightboxItems(task.attachments);
    setLightboxItems(items);
    const handleClick = (e) => {
      e.preventDefault();
      UIkit.lightboxPanel({ items }).show();
    };
    UIkit.util.on(`.js-lightbox${task.id}`, 'click', handleClick);
    return () => {
      UIkit.util.off(`.js-lightbox${task.id}`, 'click', handleClick);
    };
}, [task.attachments]);

  const [percentage, setPercentage] = useState(0);
  const calculatePercentage = () => {
    let count = task.subtasks.length;
    let completedPercentage = 0;

    for (let i = 0; i < count; i++) {
      if (task.subtasks[i].status === "DONE") completedPercentage += 1.0;
      if (task.subtasks[i].status === "IN_PROGRESS") completedPercentage += 0.1;
    }

    if (count > 0) {
      completedPercentage = (completedPercentage * 100) / count;
    } else if (task.status === "DONE") {
      completedPercentage = 100;
    }

    setPercentage(completedPercentage);
  };
  
  useEffect(() => {
    calculatePercentage();
  }, [task]);


  const [isEditing, setIsEditing] = useState(false);
  const toggleEdit = () => {
    setIsEditing(!isEditing);

    if (!isEditing) {
      setTitle(task.title);
      setDescription(task.description);
      setDueDate(task.end_at.split('T')[0]);
      setPriority(task.priority);
      setCategory(task.category);
    }
  };

  const saveTask = () => {
    const updatedTask = {
      ...task,
      title,
      description,
      end_at: new Date(dueDate).toISOString(),
      priority,
      category
    };

    updateTask(updatedTask);

    task.title = updatedTask.title;
    task.description = updatedTask.description;
    task.end_at = updatedTask.end_at;
    task.priority = updatedTask.priority;
    task.category = updatedTask.category;

    setIsEditing(false);
  };

  const toggleStatus = (event) => {
    if (status === 'TODO') {
      setStatus('IN_PROGRESS');
      event.target.checked = true;
    } else if (status === 'IN_PROGRESS') {
      setStatus('DONE');
      event.target.checked = true;
    } else if (status === 'DONE') {
      setStatus('TODO');
      event.target.checked = false;
    }

    const updatedTask = {
      ...task,
      status
    };

    updateTask(updatedTask);

    task.status = updatedTask.status;
  };

  const removeTask = () => {
    deleteTask(id);
  };

  const [showDescription, setShowDescription] = useState(false);
  const toggleDescription = () => {
    setShowDescription(!showDescription);
  };

  const openSubtaskModal = () => {
    setIsSubtask(true);
    UIkit.modal('#add-task').show();
  };

  return (
    <>
    <article
      className="uk-comment uk-visible-toggle"
      tabIndex="-1"
      role="comment"
      style={{ borderColor: cat[task.category]?.color }}
    >
      <div className={`task uk-margin-large uk-card uk-card-default ${task.priority.toLowerCase()}`}>
        <div className="settings uk-position-top-right uk-position-medium@l uk-hidden-hover">
          <div className="uk-inline uk-align-right">
            <button className="uk-button uk-button-text" type="button">
              <span uk-icon="icon: cog"></span> Settings
            </button>
            <div uk-dropdown="mode: click">
              <ul className="uk-iconnav uk-iconnav-vertical">
                <li><a href='' uk-toggle={`target: #attach${task.id}`} onClick={() => setId(task.id)}><span uk-icon="icon: settings"></span> Attachments</a></li>
                <li><a className="uk-link-muted" onClick={toggleEdit}><span uk-icon="icon: pencil"></span> Edit task</a></li>
                <li><a id={`dialog${task.id}`} href="#" onClick={() => setId(task.id)}><span uk-icon="icon: trash"></span> Delete task</a></li>
                <li><a className="uk-link-muted" onClick={openSubtaskModal}><span uk-icon="icon: plus"></span> Add Subtask</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div hidden={isEditing}>
          <header className="uk-child-width-1-1 uk-child-width-1-2@m uk-child-width-1-2@l uk-child-width-1-2@xl" uk-grid="true">
            <div>
              <div className="uk-child-width-1-2 uk-text-center" uk-grid="true">
                <div className="uk-width-auto">
                  <input type="checkbox" name="status" checked={status !== 'TODO'} onChange={toggleStatus} />
                </div>
                <div className="uk-width-expand uk-text-left uk-margin-small-left">
                  <h2
                    className="title uk-align-left"
                    style={{ textDecoration: task.status === "DONE" ? "line-through" : "none" }}
                    name="title">
                    {task.title}
                  </h2>
                </div>
              </div>
            </div>
            <div>
              <div className="uk-child-width-1-2 uk-child-width-1-3@s uk-text-center" uk-grid="true">
                <div>
                  <p>{percentage.toFixed(0)}% completed
                    {task.attachments?.length > 0 && (
                      <span id={`js-lightbox${task.id}`} className={`uk-icon uk-icon-image js-lightbox${task.id}`} style={{ backgroundImage: 'url(/img/paperclip.svg)' }}></span>
                    )}
                  </p>
                  {task.description && (
                    <span className="uk-button uk-button-text" style={{ margin: '0px !important' }} onClick={toggleDescription}>
                      {showDescription ? 'Hide description' : 'Show description'}
                    </span>
                  )}
                <div className="uk-hidden uk-visible@s"></div>
              </div>
              <div>
                <div>
                  <h4 className="due-date uk-text-right uk-text-left@m uk-margin-medium-left@s">{new Date(task.end_at).toLocaleDateString()} </h4>
                </div>
                <div id={`slider${task.id}`} uk-slider="true">
                    <div className={`uk-position-relative uk-visible@m uk-visible@l uk-visible@xl js-lightbox${task.id}`}>
                        <div className="uk-slider-container uk-light">
                            <div className="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-3@m">
                                {task.attachments.map((attach, index) => (
                                <div key={index} className="uk-cover-container">
                                    <canvas width="80" height="40"></canvas>
                                    {attach.type === 'IMAGE' && <img src={`/files/${attach.path}`} alt={attach.path} uk-cover="true" />}
                                    {attach.type === 'FILE' && (
                                    <iframe src={`/files/${attach.path}`} alt={attach.path} uk-responsive="true" uk-cover="true" uk-video="automute: true"></iframe>
                                    )}
                                    {attach.type === 'VOICE' && (
                                    <video src={`/files/${attach.path}`} alt={attach.path} uk-responsive="true" uk-cover="true" className="uk-position-center" uk-video="autoplay: false" poster="/img/play-button.svg" style={{ width: '2vw' }}></video>
                                    )}
                                </div>
                                ))}
                            </div>
                                <a className="uk-position-top-left-out uk-position-small uk-overlay uk-hidden-hover" href="#" uk-slidenav-previous="true" uk-slider-item="previous"></a>
                                <a className="uk-position-top-right-out uk-position-small uk-overlay uk-hidden-hover" href="#" uk-slidenav-next="true" uk-slider-item="next"></a>
                            </div>
                            <ul className="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>
                        </div>
                    </div>
              </div>
            </div>
            </div>
          </header>
          {task.description && (
            <div className="description uk-child-width-1-1 uk-card-body uk-text-left uk-padding-medium uk-margin-small-bottom" uk-grid="true" hidden={!showDescription}>
              <div className="descript">
                <p>{task.description}</p>
              </div>
            </div>
          )}
          <div className="third uk-text-center" uk-grid="true">
            <div className="uk-width-1-6@m uk-width-1-2 uk-position-bottom-right uk-text-right uk-position-small">
              {task.is_parent && <a href="" className="uk-button uk-button-text uk-link-muted" uk-toggle={`target: .subtask${task.id}`}>Show subtasks</a>}
            </div>
          </div>
        </div>
        <div hidden={!isEditing}>
          <form>
            <header className="uk-child-width-1-1 uk-child-width-1-2@m uk-child-width-1-2@l uk-child-width-1-2@xl" uk-grid="true">
              <div>
                <div className="uk-child-width-1-2 uk-text-center" uk-grid="true">
                  <div className="uk-width-auto">
                    <input id={`status${task.id}`} type="checkbox" name="status" disabled checked />
                  </div>
                  <div className="uk-width-expand uk-text-left uk-margin-small-left">
                    <textarea
                      id={`title${task.id}`}
                      className="title uk-textarea"
                      name="title"
                      value={title}
                      rows="2"
                      onChange={(e) => setTitle(e.target.value)}
                    />
                  </div>
                </div>
              </div>
              <div>
                <div className="uk-child-width-1-2 uk-child-width-1-3@s uk-text-center" uk-grid="true">
                  <div>
                    <div className="uk-margin">
                      <select
                        id={`priority${task.id}`}
                        className="uk-select"
                        name="category"
                        value={category}
                        onChange={(e) => setCategory(e.target.value)}
                      >
                        {categories.map((cat) => (
                          <option key={cat.id} value={cat.id}>{cat.name}</option>
                        ))}
                      </select>
                    </div>
                    
                    <div className="uk-hidden uk-visible@s"></div>
                  </div>
                    <div>
                      <input
                        id={`due_date${task.id}`}
                        type="date"
                        name="due_date"
                        className="due-date  uk-input"
                        value={dueDate}
                        onChange={(e) => setDueDate(e.target.value)}
                      />
                    </div>
                  <div>
                  </div>
                </div>
                <div>
                  <div className="uk-margin uk-grid-small uk-child-width-auto uk-grid">
                    <label><input id={`priorityL${task.id}`} className="uk-radio" type="radio" name="radio" value="LOW" checked={priority === 'LOW'} onChange={() => setPriority('LOW')} />&nbsp;Low</label>
                    <label><input id={`priorityM${task.id}`} className="uk-radio" type="radio" name="radio" value="MEDIUM" checked={priority === 'MEDIUM'} onChange={() => setPriority('MEDIUM')} />&nbsp;Medium</label>
                    <label><input id={`priorityH${task.id}`} className="uk-radio" type="radio" name="radio" value="HIGH" checked={priority === 'HIGH'} onChange={() => setPriority('HIGH')} />&nbsp;High</label>
                    <label><input id={`priorityU${task.id}`} className="uk-radio" type="radio" name="radio" value="URGENT" checked={priority === 'URGENT'} onChange={() => setPriority('URGENT')} />&nbsp;Urgent</label>
                  </div>
                </div>
              </div>
            </header>
            {task.description != null && (
            <div className="description uk-child-width-1-1 uk-card-body uk-text-left uk-padding-medium uk-margin-small-bottom" uk-grid="true">
              <div className="descript">
                <textarea
                  id={`description${task.id}`}
                  className="descr uk-textarea"
                  rows="3"
                  name="description"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                />
              </div>
            </div>
            )}
            <div className="third uk-text-center" uk-grid="true">
              <div className="uk-width-1-6@m uk-width-1-2 uk-position-bottom-right uk-text-right uk-position-small">
                <div className="uk-flex">
                  <button className="uk-button uk-button-default" type="button" onClick={toggleEdit}>Cancel</button>
                  <button className="uk-button uk-button-primary" type="button" onClick={saveTask}>Save</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
      <AddTask is_subtask={isSubtask} onSave={() => setIsSubtask(false)} />
      <Attachement id={task.id} attachments={task.attachments} />
    </article>
    <ul className={"subtask" + task.id} hidden>
    {task.subtasks != null && task.subtasks.map((subtask) => (
        <li key={subtask.id}>
            <Task task={subtask}/>
            <Attachement id={subtask.id} attachments={subtask.attachments}/>
        </li>
    ))}
    </ul>
    </>
  );
};

export default Task;
